name: Trigger Playwright Tests

on:
  pull_request:
    branches:
      - main

jobs:
  serve:
    runs-on: ubuntu-latest
    steps:

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      # Step 1: Checkout the main application repo
      - name: Checkout main application repo
        uses: actions/checkout@v2
        with:
          path: app

      #Step 2: Install and Start
      - name: Start the App
        run: |
          cd app
          npm install
          npm start &  # Run the app in the background
          sleep 5       # Adjust time depending on your app's startup time


      - name: Clone Test Suite
        run: |
          git clone --depth 1 --branch main https://x-access-token:${{ secrets.PLAYWRIGHT_TEST_REPO_TOKEN }}@github.com/dtoth-mono/playwright-suite.git test-suite
          cd test-suite
          npm ci
          npx playwright install --with-deps

      - name: Run Test Suite
        id: playwright_tests
        continue-on-error: true
        run: |
          cd test-suite
          PLAYWRIGHT_JSON_OUTPUT_FILE=results.json npx playwright test --reporter=json
          exit_code=$?
          if [ $exit_code -ne 0 ]; then
            echo "TEST_FAILED=true" >> $GITHUB_OUTPUT
          else
            echo "TEST_FAILED=false" >> $GITHUB_OUTPUT
          fi
          exit $exit_code

      - name: Playwright issue creator
        if: ${{ !cancelled() }}
        uses: estruyf/playwright-github-issue-creator@v1.3.0
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          report-path: test-suite/results.json
          issue-prefix: "E2E: "
          issue-labels: "playwright, bug"
          add-project-label: true
          add-comment: true
          job-summary: true

      - name: Upload HTML report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/**

      - name: Fail The Workflow if tests failed
        if: ${{ steps.playwright_tests.TEST_FAILED == 'true'}}
        uses: actions/github-script@v3
        with:
          script: |
            core.setFailed('Some Tests Failed')

