name: Trigger Playwright Tests

on:
  pull_request:
    branches:
      - main

jobs:
  trigger-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Playwright Test Repository
        run: |
          curl -X POST -H "Authorization: token ${{ secrets.PLAYWRIGHT_TEST_REPO_TOKEN }}" \
               -H "Accept: application/vnd.github.v3+json" \
               https://api.github.com/repos/dtoth-mono/playwright-suite/actions/workflows/playwright.yml/dispatches \
               -d '{
                 "ref": "main",
                 "inputs": {
                   "repo": "${{ github.repository }}",
                   "branch": "${{ github.head_ref }}"
                 }
               }'